// Tailwind class-string map replacing Cart.module.css
const styles = {
  cartContainer: "bg-[#f8fafc] max-w-[1200px] mx-auto px-[8%] py-[70px] text-[#1a1a1a] min-h-[70vh] max-md:px-[5%] max-md:py-10",
  cartPageTitle: "font-['Playfair_Display','Noto_Serif_Armenian',serif] text-[32px] text-[#1a1a1a] mb-10",
  emptyCartWrapper: "text-center flex flex-col justify-center items-center",
  emptyCartH2: "font-['Playfair_Display','Noto_Serif_Armenian',serif] text-[#1a1a1a] mb-2.5",
  emptyCartP: "text-[#718096]",
  cartContent: "flex gap-[30px] flex-wrap items-start",
  cartItemsList: "flex-[2] flex flex-col gap-5 min-w-[320px]",
  cartItemCard: "flex items-center bg-white border border-[#f1f5f9] p-[15px] rounded-[20px] gap-5 shadow-[0_10px_30px_rgba(0,0,0,0.03)] transition-all duration-300 hover:shadow-[0_10px_30px_rgba(0,0,0,0.08)] hover:-translate-y-[3px] max-md:flex-wrap",
  cartItemImage: "w-20 h-[110px] object-contain bg-[#f1f5f9] rounded-xl p-1.5 box-border",
  cartItemDetails: "flex-[2]",
  cartItemDetailsH3: "font-['Playfair_Display','Noto_Serif_Armenian',serif] text-[#1a1a1a] mb-[5px] text-[1.15rem]",
  cartItemAuthor: "text-[#718096] text-[0.9rem] mb-[5px]",
  cartItemPrice: "text-[#8e44ad] font-bold m-0",
  cartItemQuantity: "flex items-center gap-3 bg-[#f1f5f9] px-2.5 py-1.5 rounded-xl",
  qtyBtn: "bg-transparent border-none text-[#1a1a1a] text-[1.2rem] cursor-pointer w-[25px] h-[25px] transition-colors duration-200 hover:text-[#8e44ad]",
  qtyNumber: "text-base font-semibold min-w-[20px] text-center text-[#1a1a1a]",
  cartItemDeleteBtn: "bg-transparent border-none text-[#e74c3c] text-[1.2rem] cursor-pointer p-2.5 transition-transform duration-200 hover:scale-[1.15]",
  cartSummaryPanel: "flex-1 bg-white border border-[#edf2f7] px-[25px] py-[30px] rounded-[20px] min-w-[280px] h-fit shadow-[0_10px_30px_rgba(0,0,0,0.04)]",
  cartSummaryPanelH3: "font-['Playfair_Display','Noto_Serif_Armenian',serif] text-[#1a1a1a] mt-0",
  summaryDivider: "border-0 border-t border-[#edf2f7] my-[15px]",
  summaryRow: "flex justify-between mb-3 text-[#718096] text-[0.95rem]",
  totalPriceRow: "text-[1.2rem] text-[#1a1a1a] font-bold mt-5",
  goldText: "text-[#8e44ad]",
  checkoutBtn: "w-full p-[14px] bg-[#1a1a1a] text-white border-none rounded-xl font-semibold cursor-pointer mt-5 transition-colors duration-300 hover:bg-[#8e44ad]",
  clearCartBtn: "w-full p-3 bg-white text-[#e74c3c] border border-[#e74c3c] rounded-xl mt-2.5 cursor-pointer font-semibold transition-all duration-300 hover:bg-[#e74c3c] hover:text-white",
  orderFormContainer: "bg-white p-10 rounded-3xl shadow-[0_10px_30px_rgba(0,0,0,0.04)] border border-[#edf2f7] max-w-[500px] mx-auto my-5 text-center",
  orderFormContainerH3: "font-['Playfair_Display','Noto_Serif_Armenian',serif] text-[#1a1a1a]",
  orderInput: "block w-full px-5 py-3.5 my-2.5 border border-[#e2e8f0] rounded-xl text-base box-border font-[inherit] focus:outline-none focus:border-[#8e44ad]",
  orderCheckoutBtn: "w-full bg-[#8e44ad] text-white border-none py-[15px] mt-2.5 rounded-xl cursor-pointer text-base font-semibold hover:bg-[#6c3483]",
  orderClearCartBtn: "w-full bg-white text-[#718096] border border-[#e2e8f0] py-3 mt-2.5 rounded-xl cursor-pointer font-semibold hover:bg-[#f1f5f9] hover:text-[#1a1a1a]",
};

export default styles;
