// Tailwind class-string map replacing Shop.module.css
const styles = {
  shopContainer: "px-[10%] py-20 bg-[#f8fafc] min-h-screen",
  adminFormContainer: "bg-white p-10 rounded-3xl shadow-[0_10px_30px_rgba(0,0,0,0.04)] mb-[60px] border border-[#edf2f7]",
  adminFormContainerH3: "font-['Playfair_Display','Noto_Serif_Armenian',serif] text-[28px] mb-[25px] text-[#1a1a1a]",
  form: "flex gap-[15px] flex-wrap",
  formInput: "py-3 px-5 border border-[#e2e8f0] rounded-xl flex-1 min-w-[200px]",
  submitBtn: "bg-[#8e44ad] text-white border-none px-[25px] py-3 rounded-xl font-semibold cursor-pointer transition-colors duration-300 hover:bg-[#6c3483]",
  searchInput: "w-full max-w-[600px] px-[30px] py-[18px] mx-auto mb-[50px] block border-2 border-transparent rounded-full text-base bg-white shadow-[0_4px_20px_rgba(0,0,0,0.05)] outline-none transition-[0.3s] focus:border-[#8e44ad]",
  fileInput: "hidden",
  fileLabel: "px-5 py-3 bg-[#f1f5f9] text-[#4a5568] rounded-xl cursor-pointer text-center font-medium transition-[0.3s] border border-dashed border-[#cbd5e0] hover:bg-[#e2e8f0] hover:border-[#8e44ad] hover:text-[#8e44ad]",
  genreSelect: "py-3 px-5 border border-[#e2e8f0] rounded-xl flex-1 min-w-[200px] bg-white text-[#1a1a1a] cursor-pointer",
  descriptionInput: "py-3 px-5 border border-[#e2e8f0] rounded-xl flex-[1_1_100%] min-w-[200px] min-h-[90px] font-[inherit] resize-y",
  shopLayout: "flex items-start gap-10 max-md:flex-col",
  genreSidebar: "flex-[0_0_220px] sticky top-[100px] bg-white rounded-[20px] px-5 py-[25px] border border-[#edf2f7] shadow-[0_10px_30px_rgba(0,0,0,0.03)] max-md:w-full max-md:static max-md:flex-none",
  genreSidebarTitle: "font-['Playfair_Display','Noto_Serif_Armenian',serif] text-xl mb-[18px] text-[#1a1a1a]",
  genreList: "list-none m-0 p-0 flex flex-col gap-1.5 max-md:flex-row max-md:flex-wrap",
  genreBtn: "w-full text-left bg-none border-none px-3.5 py-2.5 rounded-[10px] text-[15px] text-[#4a5568] cursor-pointer transition-[0.25s] hover:bg-[#f1f5f9] hover:text-[#8e44ad] max-md:w-auto",
  activeGenreBtn: "!bg-[#8e44ad] !text-white font-semibold hover:!bg-[#6c3483]",
  genreTag: "block self-start text-[18px] font-bold text-[#8e44ad] bg-[#f3e8f8] px-2.5 py-1 rounded-full mb-[15px]",
  noResults: "col-span-full text-center text-[#718096] text-base py-10",
  booksGrid: "flex-1 grid grid-cols-[repeat(auto-fill,minmax(280px,1fr))] gap-10",
  bookCard: "bg-white p-5 rounded-3xl transition-all duration-500 border border-[#f1f5f9] text-left flex flex-col hover:-translate-y-[15px] hover:shadow-[0_20px_40px_rgba(0,0,0,0.08)]",
  bookCardImg: "w-full h-[350px] object-contain bg-[#f1f5f9] rounded-2xl mb-5 p-3 box-border",
  imageWrapper: "relative",
  favBtn: "absolute top-2.5 right-2.5 w-[38px] h-[38px] rounded-full border-none bg-[rgba(255,255,255,0.9)] text-[#b0b7c3] text-lg flex items-center justify-center cursor-pointer shadow-[0_2px_8px_rgba(0,0,0,0.1)] transition-[0.2s] hover:text-[#e74c3c] hover:scale-110",
  favBtnActive: "text-[#e74c3c]",
  bookCardH3: "font-['Playfair_Display','Noto_Serif_Armenian',serif] text-[22px] my-0 mb-[5px]",
  bookCardP: "text-[#718096] mb-[15px]",
  bookCardPriceSpan: "font-bold text-lg text-[#8e44ad] block mb-[15px]",
  buyBtn: "bg-[#1a1a1a] text-white border-none p-3.5 rounded-xl font-semibold cursor-pointer transition-[0.3s] flex-1 hover:bg-[#8e44ad]",
  bookCardActions: "flex gap-2.5 mt-auto",
  viewBtn: "flex-none bg-white text-[#1a1a1a] border border-[#1a1a1a] px-[18px] py-3.5 rounded-xl font-semibold cursor-pointer transition-[0.3s] no-underline text-center whitespace-nowrap hover:bg-[#1a1a1a] hover:text-white",
  adminBookActions: "flex gap-2 self-start",
  deleteBtn: "bg-white text-[#e74c3c] border border-[#e74c3c] p-2.5 rounded-[10px] cursor-pointer transition-all duration-300 mt-2.5 text-base hover:bg-[#e74c3c] hover:text-white hover:scale-105",
  editBtn: "bg-white text-[#8e44ad] border border-[#8e44ad] p-2.5 rounded-[10px] cursor-pointer transition-all duration-300 mt-2.5 text-base hover:bg-[#8e44ad] hover:text-white hover:scale-105",
  loading: "text-center py-[100px] font-['Playfair_Display','Noto_Serif_Armenian',serif] text-2xl",
};

export default styles;
